version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - 85:85
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433